### ISSUE TITLE
New line indentation

### ISSUE THREAD

**Issue by asiniy** [flying-sheep/babel-plugin-transform-react-createelement-to-jsx#1]
Huge thanks for you for this plugin!

I found just one drawback. Plugin pose all `JSX` tags just in one line. How can I avoid it?

**Comment by flying-sheep** [comment]
> Huge thanks for you for this plugin!

i’m glad it’s useful for you!

> I found just one drawback. Plugin pose all `JSX` tags just in one line. How can I avoid it?

i don’t know, but maybe we can find out together.

do you know how babel/ESTree represents whitespace?

**Comment by asiniy** [comment]
Unfortunately, nope.

**Comment by flying-sheep** [comment]
so you say

``` js
<ol>
    <li>a</li>
    <li>b</li>
</ol>
```

gets converted to

``` js
<ol><li>a</li><li>b</li></ol>
```

or what?

**Comment by asiniy** [comment]
I mean

``` javascript
React.createElement("ul", React.createElement("li"))
```

converts to

```
<ul><li></li></ul>
```

not

```
<ul>
  <li></li>
</ul>
```

**Comment by flying-sheep** [comment]
well, that’s correct, no?

``` js
React.createElement("ul",
    React.createElement("li")
)
```

should convert to

``` js
<ul>
  <li></li>
</ul>
```

or similar.

**Comment by foxyblocks** [comment]
It's not just JSX. I noticed that it did this for simple arrays also. I tried with a simple example:

Before:

``` js
let my_list = [
  "one",
  "two",
  "three",
  "four"
];
```

after: 

``` js
let my_list = ["one", "two", "three", "four"];
```

**Comment by flying-sheep** [comment]
huh? that’s really weird, as [i only replace nodes that pass all the checks](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx/blob/08ad8c0b55e7aa6cf17ce7fa3568470f76de05d4/src/index.js#L127-L129) (i.e. are `React.createElement` calls, etc.)

is what you observe inside of such an expression or will a file containing only what you showed me be transformed like that?

**Comment by foxyblocks** [comment]
Only what I showed you. It's a file containing only an array

**Comment by foxyblocks** [comment]
Adding the following to the test file will reproduce this:

``` js
it('should ignore regular javascript arrays', () => {
    let source = `
      let list = [
        "one",
        "two",
        "three",
      ]
    `
  expect(source).to.convertTo(source)
})

```

results in:

```
  1) createElement-to-JSX should ignore regular javascript arrays:

      Code “
      let list = [
        "one",
        "two",
        "three",
      ]
    ” converts wrongly
      + expected - actual


      -let list = ["one", "two", "three"];
      +      let list = [
      +        "one",
      +        "two",
      +        "three",
      +      ]
      +

      at Assertion.<anonymous> (test/chai-convert-to.js:62:41)
      at Assertion.ctx.(anonymous function) [as convertTo] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Context.<anonymous> (test/index.js:72:21)

```

I'll try to debug further, to see if I can't get to the bottom of it.

**Comment by foxyblocks** [comment]
Further investigation shows that this is a problem with babel itself. I can reproduce it by running babel without any plugin options. Using the `babel --retain-lines` flag can mostly mitigate it, but not perfectly:

before

``` js
let foo = [
  'one',
  'two',
  'three'
];
```

after

``` js
let foo = [
'one',
'two',
'three'];
```

**Comment by flying-sheep** [comment]
OK, so it’s not actually a bug and i can close it, right?

**Comment by foxyblocks** [comment]
I should think so

**Comment by flying-sheep** [comment]
OK, thanks for investigating!
