### ISSUE TITLE
Use with other plugins

### ISSUE THREAD

**Issue by andevsoftware** [flying-sheep/babel-plugin-transform-react-createelement-to-jsx#3]
When I execute 

```
babel --plugins transform-react-createelement-to-jsx component.js --out-file component.jsx  
```

I get the following error

```
SyntaxError: workspace.js: Unexpected token (13:14)
  11 |     class Component extends React.Component {
  12 | 
> 13 |         state = {
```

When I execute

```
babel --plugins transform-react-createelement-to-jsx,transform-class-properties workspace.js --out-file workspace.jsx  
```

It compiles but the class properties are transformed, I want just the createElement syntax to be jsx. Do you know if there is any option to do that?

**Comment by flying-sheep** [comment]
just use [syntax-class-properties](https://www.npmjs.com/package/babel-plugin-syntax-class-properties)!
