### ISSUE TITLE
How to convert the reactjs file to jsx ?

### ISSUE THREAD

**Issue by Sulaiman90** [flying-sheep/babel-plugin-transform-react-createelement-to-jsx#7]
Can anyone please tell me how to convert the js file to jsx ?. 
Readme file shows how to install the plugin and I dont know how to make it work ?.

**Comment by flying-sheep** [comment]
It does, in [Usage](https://github.com/flying-sheep/babel-plugin-transform-react-createelement-to-jsx#usage)

**Comment by Sulaiman90** [comment]
okay. thanks. Got it
